# Generated by Django 3.2 on 2021-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eve_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(verbose_name='Event Date'),
        ),
    ]
