# Generated by Django 3.2 on 2021-05-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='type',
        ),
    ]
