# Generated by Django 3.2 on 2021-05-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='booking_rates',
            field=models.FloatField(blank=True, default=1.0, verbose_name='Ranking (up to 9.9)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='flour_size',
            field=models.FloatField(blank=True, default=1.0, verbose_name='Square (mxm)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='from_hour',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='to_hour',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='web',
            field=models.URLField(blank=True, verbose_name='Website Address'),
        ),
    ]
