# Generated by Django 3.2 on 2021-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='booking_rates',
            field=models.FloatField(blank=True, default=1.0, verbose_name='Ranking (up to 9.0)'),
        ),
    ]
